services:

  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=insights

#  insights:
#    image: jan310/insights:0.1
#    container_name: insights
#    ports:
#      - 8080:8080
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_USER=user
#      - DB_PASSWORD=password
#      - DB_NAME=insights
