CREATE TABLE USERS
(
    ID          BIGSERIAL       PRIMARY KEY,
    AUTH0_ID    VARCHAR(50)     UNIQUE NOT NULL,
    EMAIL       VARCHAR(255)    UNIQUE NOT NULL
);

CREATE TABLE INSIGHTS
(
    ID          BIGSERIAL       PRIMARY KEY,
    CONTENT     TEXT            NOT NULL,
    SOURCE_TYPE VARCHAR(30)     NOT NULL,
    SOURCE      JSONB           NOT NULL
);
